name: "scene_appearance"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 42

data_type: "global-local-camera-datamodule"
data:
  global_camera_type: "layout-aware-camera-datamodule"
  global_camera:
    batch_size: 1
    width: 512
    height: 512
    fovy_range: [30., 60.]
    camera_perturb: 0.
    up_perturb: 0.
    eval_fovy_deg: 55.
    test_all: true
    camera_path: ???

  local_camera_type: "random-multiview-camera-datamodule"
  local_camera:
    batch_size: 1
    width: 512
    height: 512
    camera_distance_range: [0.8, 1.0]
    relative_distance: true
    fovy_range: [40., 45.]
    elevation_range: [0., 30.]
    camera_perturb: 0.0
    center_perturb: 0.0
    up_perturb: 0.0
    eval_elevation_deg: 15.
    eval_camera_distance: 3.0
    eval_fovy_deg: 45.
    n_view: 4

system_type: "layout2gs-system"
system:
  mode: "appearance"

  geometry_type: "textured-mesh"
  geometry:
    init_strategy: "from_layout"
    init_file_path: ???
    is_local_space: true
    texture_type: field2d
    pos_encoding_config:
      otype: "HashGrid"
      n_levels: 20
      n_features_per_level: 4
      log2_hashmap_size: 24
      base_resolution: 16
      per_level_scale: 1.447269237440378
    mlp_network_config:
      otype: "VanillaMLP"
      activation: "ReLU"
      output_activation: "none"
      n_neurons: 128
      n_hidden_layers: 5

  material_type: "no-material"
  material:
    color_activation: "scale_-11_01"

  background_type: "solid-color-background"
  background:
    color: [.5, .5, .5]

  renderer_type: "nvdiff-rasterizer-ex"

  exporter_type: "textured-mesh-exporter"

  prompt_processor_type: "global-local-prompt-processor"
  prompt_processor:
    global_prompt_processor_type: "stable-diffusion-prompt-processor"
    global_prompt_processor:
      # pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
      pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
      prompt: ""
      negative_prompt: "deformed, extra digit, fewer digits, cropped, worst quality, low quality, smoke, shading, lighting, lumination, shadow, text in image, watermarks"
    local_prompt_processor_type: "stable-diffusion-prompt-processor"
    local_prompt_processor:
      pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
      negative_prompt: "deformed, extra digit, fewer digits, cropped, worst quality, low quality, smoke, shading, lighting, lumination, shadow, text in image, watermarks"
    local_prompt_init_strategy: "from_layout"
    local_prompt_init_file_path: ???
    local_additional_prompt: ""

  ctrl_appearance_guidance_type: "multi-controlnet-guidance"
  ctrl_appearance_guidance:
    # pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    controlnet_pretrained_model_name_or_path: [
      "lllyasviel/control_v11p_sd15_seg", 
      "lllyasviel/control_v11p_sd15_normalbae", 
      "lllyasviel/control_v11p_sd15_depth",
    ]
    guidance_scale: 7.5
    guidance_type: isd
    weighting_strategy: fantasia3d
    min_step_percent: 0.02
    max_step_percent: 0.98
    view_dependent_prompting: false
    use_img_loss: false
    controlnet_conditioning_scale: [
      1.0, 
      1.0, 
      1.0,
    ]
    controlnet_guess_mode: false
    condition_keys: [
      "comp_semantic", 
      "comp_normal", 
      "comp_depth",
    ]

  # local_appearance_guidance_type: "multi-controlnet-guidance"
  # local_appearance_guidance:
  #   pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
  #   controlnet_pretrained_model_name_or_path: [
  #     "lllyasviel/control_v11p_sd15_normalbae",
  #     # "lllyasviel/control_v11p_sd15_depth",
  #   ]
  #   guidance_scale: 100.
  #   guidance_type: sds
  #   weighting_strategy: sds
  #   min_step_percent: 0.02
  #   max_step_percent: 0.98
  #   view_dependent_prompting: true
  #   use_img_loss: false
  #   controlnet_conditioning_scale: [
  #     1.0,
  #     # 1.0,
  #   ]
  #   controlnet_guess_mode: false
  #   condition_keys: [
  #     "comp_normal", 
  #     # "comp_depth",
  #   ]

  freq:
    guidance_eval: 100

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_ctrl_appearance_sds: 1.
    lambda_ctrl_appearance_sds_img: 1.
    lambda_local_appearance_sds: 1.
    lambda_local_appearance_sds_img: 1.

  optimizer:
    name: RAdam
    args:
      lr: 0.0
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry.encoding:
        lr: 1e-3
      geometry.network:
        lr: 1e-3
        # weight_decay: 1e-6

trainer:
  max_steps: 10000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 10001
  enable_progress_bar: true

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
